version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "443:443"
    env_file: local.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    command: caddy run

  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: test.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    command: caddy run

  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    env_file: test.env
    depends_on:
      - testapp
      - fakemanagementapi
      - server1
      - server2
      - server3

  fakemanagementapi:
    image: caddy:latest
    environment:
      - RESPONSE=API
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run
  server1:
    image: caddy:latest
    environment:
      - RESPONSE=1
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run
  server2:
    image: caddy:latest
    environment:
      - RESPONSE=2
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run
  server3:
    image: caddy:latest
    environment:
      - RESPONSE=3
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run
