version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "443:443"
    env_file: local.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run

  testapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8999:8888"
      - "443:443"
    env_file: test.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run

  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    env_file: test.env

  fakemanagementapi:
    image: lipanski/docker-static-website:latest
    ports:
      - "8900:3000"
    volumes:
      - ./site:/home/static
  server1:
    image: lipanski/docker-static-website:latest
    ports:
      - "8901:3000"
    volumes:
      - ./site/1.txt:/home/static/1.txt
  server2:
    image: lipanski/docker-static-website:latest
    ports:
      - "8902:3000"
    volumes:
      - ./site/2.txt:/home/static/2.txt
  server3:
    image: lipanski/docker-static-website:latest
    ports:
      - "8903:3000"
    volumes:
      - ./site/3.txt:/home/static/3.txt

volumes:
  caddy_data:
    external: true
  caddy_config:

