version: "3.7"

services:
  caddy:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
        - "8888:8888"
        - "443:443"
        - "2019:2019"
    env_file: ./local.env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    command: xcaddy run

volumes:
  caddy_data:
    external: true
  caddy_config:

