version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "53060:80"
      - "53061:443"
      - "53062:2019"
    env_file: local.env
    volumes:
      - ./:/app

  testapp:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "53063:80"
    env_file: test.env
    volumes:
      - ./:/app

  test:
    image: golang:1.18
    env_file: test.env
    volumes:
      - .:/src
    working_dir: /src
    depends_on:
      - testapp
      - fakemanagementapi
      - server1
      - server2
      - server3

  fakemanagementapi:
    image: caddy:latest
    environment:
      SERVER: API
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run

  server1:
    image: caddy:latest
    environment:
      SERVER: server1
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run

  server2:
    image: caddy:latest
    environment:
      SERVER: server2
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run

  server3:
    image: caddy:latest
    environment:
      SERVER: server3
    volumes:
      - ./Caddyfile-test:/srv/Caddyfile
    command: caddy run
