include:
  - docker-compose.test.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "53060:80"
      - "53061:443"
      - "53062:2019"
    env_file: local.env
    volumes:
      - ./:/app
      - go-build:/root/.cache/go-build
      - go-mod:/go/pkg/mod
